Table "actions" {
  "id" varchar(24) [pk, not null]
  "resource_id" varchar(24)
  "resource_type" varchar(50) [not null]
  "actor_id" varchar(24) [not null]
  "actor_type" varchar(50) [not null]
  "event" varchar(50) [not null]
  "context" text
  "created_at" datetime [not null]
}

Table "api_keys" {
  "id" varchar(24) [pk, not null]
  "type" varchar(50) [not null]
  "secret" varchar(191) [unique, not null]
  "role_id" varchar(24)
  "integration_id" varchar(24)
  "user_id" varchar(24)
  "last_seen_at" datetime
  "last_seen_version" varchar(50)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "automated_email_recipients" {
  "id" varchar(24) [pk, not null]
  "automated_email_id" varchar(24) [not null]
  "member_id" varchar(24) [not null]
  "member_uuid" varchar(36) [not null]
  "member_email" varchar(191) [not null]
  "member_name" varchar(191)
  "created_at" datetime [not null]
  "updated_at" datetime

  Indexes {
    member_id [type: btree, name: "automated_email_recipients_member_id_index"]
  }
}

Table "benefits" {
  "id" varchar(24) [pk, not null]
  "name" varchar(191) [not null]
  "slug" varchar(191) [unique, not null]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "brute" {
  "key" varchar(191) [pk, not null]
  "firstRequest" bigint [not null]
  "lastRequest" bigint [not null]
  "lifetime" bigint [not null]
  "count" int [not null]
}

Table "collections" {
  "id" varchar(24) [pk, not null]
  "title" varchar(191) [not null]
  "slug" varchar(191) [unique, not null]
  "description" varchar(2000)
  "type" varchar(50) [not null]
  "filter" text
  "feature_image" varchar(2000)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "collections_posts" {
  "id" varchar(24) [pk, not null]
  "collection_id" varchar(24) [not null]
  "post_id" varchar(24) [not null]
  "sort_order" "int unsigned" [not null, default: 0]
}

Table "comment_likes" {
  "id" varchar(24) [pk, not null]
  "comment_id" varchar(24) [not null]
  "member_id" varchar(24) [not null]
  "created_at" datetime [not null]
  "updated_at" datetime [not null]
}

Table "comment_reports" {
  "id" varchar(24) [pk, not null]
  "comment_id" varchar(24) [not null]
  "member_id" varchar(24)
  "created_at" datetime [not null]
  "updated_at" datetime [not null]
}

Table "comments" {
  "id" varchar(24) [pk, not null]
  "post_id" varchar(24) [not null]
  "member_id" varchar(24)
  "parent_id" varchar(24)
  "in_reply_to_id" varchar(24)
  "status" varchar(50) [not null, default: 'published']
  "html" longtext
  "edited_at" datetime
  "created_at" datetime [not null]
  "updated_at" datetime [not null]
}

Table "custom_theme_settings" {
  "id" varchar(24) [pk, not null]
  "theme" varchar(191) [not null]
  "key" varchar(191) [not null]
  "type" varchar(50) [not null]
  "value" text
}

Table "donation_payment_events" {
  "id" varchar(24) [pk, not null]
  "name" varchar(191)
  "email" varchar(191) [not null]
  "member_id" varchar(24)
  "amount" int [not null]
  "currency" varchar(50) [not null]
  "attribution_id" varchar(24)
  "attribution_type" varchar(50)
  "attribution_url" varchar(2000)
  "referrer_source" varchar(191)
  "referrer_medium" varchar(191)
  "referrer_url" varchar(2000)
  "utm_source" varchar(191)
  "utm_medium" varchar(191)
  "utm_campaign" varchar(191)
  "utm_term" varchar(191)
  "utm_content" varchar(191)
  "created_at" datetime [not null]
  "donation_message" varchar(255)
}

Table "email_batches" {
  "id" varchar(24) [pk, not null]
  "email_id" varchar(24) [not null]
  "provider_id" varchar(255)
  "fallback_sending_domain" tinyint(1) [not null, default: 0]
  "status" varchar(50) [not null, default: 'pending']
  "member_segment" text
  "error_status_code" "int unsigned"
  "error_message" varchar(2000)
  "error_data" longtext
  "created_at" datetime [not null]
  "updated_at" datetime [not null]
}

Table "email_design_settings" {
  "id" varchar(24) [pk, not null]
  "slug" varchar(191) [unique, not null]
  "background_color" varchar(50) [not null, default: 'light']
  "header_background_color" varchar(50) [not null, default: 'transparent']
  "header_image" varchar(2000)
  "show_header_icon" tinyint(1) [not null, default: 1]
  "show_header_title" tinyint(1) [not null, default: 1]
  "footer_content" text
  "button_color" varchar(50) [default: 'accent']
  "button_corners" varchar(50) [not null, default: 'rounded']
  "button_style" varchar(50) [not null, default: 'fill']
  "link_color" varchar(50) [default: 'accent']
  "link_style" varchar(50) [not null, default: 'underline']
  "body_font_category" varchar(191) [not null, default: 'sans_serif']
  "title_font_category" varchar(191) [not null, default: 'sans_serif']
  "title_font_weight" varchar(50) [not null, default: 'bold']
  "image_corners" varchar(50) [not null, default: 'square']
  "divider_color" varchar(50)
  "section_title_color" varchar(50)
  "show_badge" tinyint(1) [not null, default: 1]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "email_recipient_failures" {
  "id" varchar(24) [pk, not null]
  "email_id" varchar(24) [not null]
  "member_id" varchar(24)
  "email_recipient_id" varchar(24) [not null]
  "code" "int unsigned" [not null]
  "enhanced_code" varchar(50)
  "message" varchar(2000) [not null]
  "severity" varchar(50) [not null, default: 'permanent']
  "failed_at" datetime [not null]
  "event_id" varchar(255)
}

Table "email_recipients" {
  "id" varchar(24) [pk, not null]
  "email_id" varchar(24) [not null]
  "member_id" varchar(24) [not null]
  "batch_id" varchar(24) [not null]
  "processed_at" datetime
  "delivered_at" datetime
  "opened_at" datetime
  "failed_at" datetime
  "member_uuid" varchar(36) [not null]
  "member_email" varchar(191) [not null]
  "member_name" varchar(191)

  Indexes {
    (delivered_at, email_id) [type: btree, name: "email_recipients_email_id_delivered_at_index"]
    (failed_at, email_id) [type: btree, name: "email_recipients_email_id_failed_at_index"]
    (member_email, email_id) [type: btree, name: "email_recipients_email_id_member_email_index"]
    (opened_at, email_id) [type: btree, name: "email_recipients_email_id_opened_at_index"]
    member_id [type: btree, name: "email_recipients_member_id_index"]
  }
}

Table "email_spam_complaint_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "email_id" varchar(24) [not null]
  "email_address" varchar(191) [not null]
  "created_at" datetime [not null]

  Indexes {
    (email_id, member_id) [unique, name: "email_spam_complaint_events_email_id_member_id_unique"]
  }
}

Table "emails" {
  "id" varchar(24) [pk, not null]
  "post_id" varchar(24) [unique, not null]
  "uuid" varchar(36) [not null]
  "status" varchar(50) [not null, default: 'pending']
  "recipient_filter" text [not null]
  "error" varchar(2000)
  "error_data" longtext
  "email_count" "int unsigned" [not null, default: 0]
  "csd_email_count" "int unsigned"
  "delivered_count" "int unsigned" [not null, default: 0]
  "opened_count" "int unsigned" [not null, default: 0]
  "failed_count" "int unsigned" [not null, default: 0]
  "subject" varchar(300)
  "from" varchar(2000)
  "reply_to" varchar(2000)
  "html" longtext
  "plaintext" longtext
  "source" longtext
  "source_type" varchar(50) [not null, default: 'html']
  "track_opens" tinyint(1) [not null, default: 0]
  "track_clicks" tinyint(1) [not null, default: 0]
  "feedback_enabled" tinyint(1) [not null, default: 0]
  "submitted_at" datetime [not null]
  "newsletter_id" varchar(24)
  "created_at" datetime [not null]
  "updated_at" datetime

  Indexes {
    post_id [type: btree, name: "emails_post_id_index"]
  }
}

Table "gifts" {
  "id" varchar(24) [pk, not null]
  "token" varchar(48) [unique, not null]
  "buyer_email" varchar(191) [not null]
  "buyer_member_id" varchar(24)
  "redeemer_member_id" varchar(24)
  "tier_id" varchar(24) [not null]
  "cadence" varchar(50) [not null]
  "duration" "int unsigned" [not null]
  "currency" varchar(50) [not null]
  "amount" "int unsigned" [not null]
  "stripe_checkout_session_id" varchar(255) [unique, not null]
  "stripe_payment_intent_id" varchar(255) [unique, not null]
  "consumes_at" datetime
  "expires_at" datetime [not null]
  "status" varchar(50) [not null]
  "purchased_at" datetime [not null]
  "redeemed_at" datetime
  "consumed_at" datetime
  "expired_at" datetime
  "refunded_at" datetime
  "consumes_soon_reminder_sent_at" datetime

  Indexes {
    (consumes_at, status) [type: btree, name: "gifts_status_consumes_at_index"]
    (expires_at, status) [type: btree, name: "gifts_status_expires_at_index"]
  }
}

Table "integrations" {
  "id" varchar(24) [pk, not null]
  "type" varchar(50) [not null, default: 'custom']
  "name" varchar(191) [not null]
  "slug" varchar(191) [unique, not null]
  "icon_image" varchar(2000)
  "description" varchar(2000)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "invites" {
  "id" varchar(24) [pk, not null]
  "role_id" varchar(24) [not null]
  "status" varchar(50) [not null, default: 'pending']
  "token" varchar(191) [unique, not null]
  "email" varchar(191) [unique, not null]
  "expires" bigint [not null]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "jobs" {
  "id" varchar(24) [pk, not null]
  "name" varchar(191) [unique, not null]
  "status" varchar(50) [not null, default: 'queued']
  "started_at" datetime
  "finished_at" datetime
  "created_at" datetime [not null]
  "updated_at" datetime
  "metadata" varchar(2000)
  "queue_entry" "int unsigned"
}

Table "labels" {
  "id" varchar(24) [pk, not null]
  "name" varchar(191) [unique, not null]
  "slug" varchar(191) [unique, not null]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "members" {
  "id" varchar(24) [pk, not null]
  "uuid" varchar(36) [unique, not null]
  "transient_id" varchar(191) [unique, not null]
  "email" varchar(191) [unique, not null]
  "status" varchar(50) [not null, default: 'free']
  "name" varchar(191)
  "expertise" varchar(191)
  "note" varchar(2000)
  "geolocation" varchar(2000)
  "enable_comment_notifications" tinyint(1) [not null, default: 1]
  "email_count" "int unsigned" [not null, default: 0]
  "email_opened_count" "int unsigned" [not null, default: 0]
  "email_open_rate" "int unsigned"
  "email_disabled" tinyint(1) [not null, default: 0]
  "last_seen_at" datetime
  "last_commented_at" datetime
  "commenting" text
  "created_at" datetime [not null]
  "updated_at" datetime

  Indexes {
    (id, created_at) [type: btree, name: "members_created_at_id_index"]
    email_disabled [type: btree, name: "members_email_disabled_index"]
    email_open_rate [type: btree, name: "members_email_open_rate_index"]
  }
}

Table "members_cancel_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "from_plan" varchar(255) [not null]
  "created_at" datetime [not null]
}

Table "members_click_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "redirect_id" varchar(24) [not null]
  "created_at" datetime [not null]
}

Table "members_created_events" {
  "id" varchar(24) [pk, not null]
  "created_at" datetime [not null]
  "member_id" varchar(24) [not null]
  "attribution_id" varchar(24)
  "attribution_type" varchar(50)
  "attribution_url" varchar(2000)
  "referrer_source" varchar(191)
  "referrer_medium" varchar(191)
  "referrer_url" varchar(2000)
  "utm_source" varchar(191)
  "utm_medium" varchar(191)
  "utm_campaign" varchar(191)
  "utm_term" varchar(191)
  "utm_content" varchar(191)
  "source" varchar(50) [not null]
  "batch_id" varchar(24)

  Indexes {
    attribution_id [type: btree, name: "members_created_events_attribution_id_index"]
  }
}

Table "members_email_change_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "to_email" varchar(191) [not null]
  "from_email" varchar(191) [not null]
  "created_at" datetime [not null]
}

Table "members_feedback" {
  "id" varchar(24) [pk, not null]
  "score" "int unsigned" [not null, default: 0]
  "member_id" varchar(24) [not null]
  "post_id" varchar(24) [not null]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "members_labels" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "label_id" varchar(24) [not null]
  "sort_order" "int unsigned" [not null, default: 0]
}

Table "members_login_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "created_at" datetime [not null]
}

Table "members_newsletters" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "newsletter_id" varchar(24) [not null]

  Indexes {
    (member_id, newsletter_id) [type: btree, name: "members_newsletters_newsletter_id_member_id_index"]
  }
}

Table "members_paid_subscription_events" {
  "id" varchar(24) [pk, not null]
  "type" varchar(50)
  "member_id" varchar(24) [not null]
  "subscription_id" varchar(24)
  "from_plan" varchar(255)
  "to_plan" varchar(255)
  "currency" varchar(191) [not null]
  "source" varchar(50) [not null]
  "mrr_delta" int [not null]
  "created_at" datetime [not null]
}

Table "members_payment_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "amount" int [not null]
  "currency" varchar(191) [not null]
  "source" varchar(50) [not null]
  "created_at" datetime [not null]
}

Table "members_product_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "product_id" varchar(24) [not null]
  "action" varchar(50)
  "created_at" datetime [not null]
}

Table "members_products" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "product_id" varchar(24) [not null]
  "sort_order" "int unsigned" [not null, default: 0]
  "expiry_at" datetime
}

Table "members_status_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "from_status" varchar(50)
  "to_status" varchar(50)
  "created_at" datetime [not null]
  "batch_id" varchar(24)
}

Table "members_stripe_customers" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "customer_id" varchar(255) [unique, not null]
  "name" varchar(191)
  "email" varchar(191)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "members_stripe_customers_subscriptions" {
  "id" varchar(24) [pk, not null]
  "customer_id" varchar(255) [not null]
  "ghost_subscription_id" varchar(24)
  "subscription_id" varchar(255) [unique, not null]
  "stripe_price_id" varchar(255) [not null, default: '']
  "status" varchar(50) [not null]
  "cancel_at_period_end" tinyint(1) [not null, default: 0]
  "cancellation_reason" varchar(500)
  "current_period_end" datetime [not null]
  "start_date" datetime [not null]
  "default_payment_card_last4" varchar(4)
  "created_at" datetime [not null]
  "updated_at" datetime
  "mrr" "int unsigned" [not null, default: 0]
  "offer_id" varchar(24)
  "discount_start" datetime
  "discount_end" datetime
  "trial_start_at" datetime
  "trial_end_at" datetime
  "plan_id" varchar(255) [not null]
  "plan_nickname" varchar(50) [not null]
  "plan_interval" varchar(50) [not null]
  "plan_amount" int [not null]
  "plan_currency" varchar(191) [not null]

  Indexes {
    stripe_price_id [type: btree, name: "members_stripe_customers_subscriptions_stripe_price_id_index"]
  }
}

Table "members_subscribe_events" {
  "id" varchar(24) [pk, not null]
  "member_id" varchar(24) [not null]
  "subscribed" tinyint(1) [not null, default: 1]
  "created_at" datetime [not null]
  "source" varchar(50)
  "newsletter_id" varchar(24)

  Indexes {
    (newsletter_id, created_at) [type: btree, name: "members_subscribe_events_newsletter_id_created_at_index"]
  }
}

Table "members_subscription_created_events" {
  "id" varchar(24) [pk, not null]
  "created_at" datetime [not null]
  "member_id" varchar(24) [not null]
  "subscription_id" varchar(24) [not null]
  "attribution_id" varchar(24)
  "attribution_type" varchar(50)
  "attribution_url" varchar(2000)
  "referrer_source" varchar(191)
  "referrer_medium" varchar(191)
  "referrer_url" varchar(2000)
  "utm_source" varchar(191)
  "utm_medium" varchar(191)
  "utm_campaign" varchar(191)
  "utm_term" varchar(191)
  "utm_content" varchar(191)
  "batch_id" varchar(24)

  Indexes {
    attribution_id [type: btree, name: "members_subscription_created_events_attribution_id_index"]
  }
}

Table "mentions" {
  "id" varchar(24) [pk, not null]
  "source" varchar(2000) [not null]
  "source_title" varchar(2000)
  "source_site_title" varchar(2000)
  "source_excerpt" varchar(2000)
  "source_author" varchar(2000)
  "source_featured_image" varchar(2000)
  "source_favicon" varchar(2000)
  "target" varchar(2000) [not null]
  "resource_id" varchar(24)
  "resource_type" varchar(50)
  "created_at" datetime [not null]
  "payload" text
  "deleted" tinyint(1) [not null, default: 0]
  "verified" tinyint(1) [not null, default: 0]
}

Table "migrations" {
  "id" "int unsigned" [pk, not null, increment]
  "name" varchar(120) [not null]
  "version" varchar(70) [not null]
  "currentVersion" varchar(255)

  Indexes {
    (name, version) [unique, name: "migrations_name_version_unique"]
  }
}

Table "migrations_lock" {
  "lock_key" varchar(191) [pk, not null]
  "locked" tinyint(1) [default: 0]
  "acquired_at" datetime
  "released_at" datetime
}

Table "milestones" {
  "id" varchar(24) [pk, not null]
  "type" varchar(24) [not null]
  "value" int [not null]
  "currency" varchar(24)
  "created_at" datetime [not null]
  "email_sent_at" datetime
}

Table "mobiledoc_revisions" {
  "id" varchar(24) [pk, not null]
  "post_id" varchar(24) [not null]
  "mobiledoc" longtext
  "created_at_ts" bigint [not null]
  "created_at" datetime [not null]

  Indexes {
    post_id [type: btree, name: "mobiledoc_revisions_post_id_index"]
  }
}

Table "newsletters" {
  "id" varchar(24) [pk, not null]
  "uuid" varchar(36) [unique, not null]
  "name" varchar(191) [unique, not null]
  "description" varchar(2000)
  "feedback_enabled" tinyint(1) [not null, default: 0]
  "slug" varchar(191) [unique, not null]
  "sender_name" varchar(191)
  "sender_email" varchar(191)
  "sender_reply_to" varchar(191) [not null, default: 'newsletter']
  "status" varchar(50) [not null, default: 'active']
  "visibility" varchar(50) [not null, default: 'members']
  "subscribe_on_signup" tinyint(1) [not null, default: 1]
  "sort_order" "int unsigned" [not null, default: 0]
  "header_image" varchar(2000)
  "show_header_icon" tinyint(1) [not null, default: 1]
  "show_header_title" tinyint(1) [not null, default: 1]
  "show_excerpt" tinyint(1) [not null, default: 0]
  "title_font_category" varchar(191) [not null, default: 'sans_serif']
  "title_alignment" varchar(191) [not null, default: 'center']
  "show_feature_image" tinyint(1) [not null, default: 1]
  "body_font_category" varchar(191) [not null, default: 'sans_serif']
  "footer_content" text
  "show_badge" tinyint(1) [not null, default: 1]
  "show_header_name" tinyint(1) [not null, default: 1]
  "show_post_title_section" tinyint(1) [not null, default: 1]
  "show_comment_cta" tinyint(1) [not null, default: 1]
  "show_subscription_details" tinyint(1) [not null, default: 0]
  "show_latest_posts" tinyint(1) [not null, default: 0]
  "show_share_button" tinyint(1) [not null, default: 0]
  "background_color" varchar(50) [not null, default: 'light']
  "post_title_color" varchar(50)
  "created_at" datetime [not null]
  "updated_at" datetime
  "button_corners" varchar(50) [not null, default: 'rounded']
  "button_style" varchar(50) [not null, default: 'fill']
  "title_font_weight" varchar(50) [not null, default: 'bold']
  "link_style" varchar(50) [not null, default: 'underline']
  "image_corners" varchar(50) [not null, default: 'square']
  "header_background_color" varchar(50) [not null, default: 'transparent']
  "section_title_color" varchar(50)
  "divider_color" varchar(50)
  "button_color" varchar(50) [default: 'accent']
  "link_color" varchar(50) [default: 'accent']
}

Table "offer_redemptions" {
  "id" varchar(24) [pk, not null]
  "offer_id" varchar(24) [not null]
  "member_id" varchar(24) [not null]
  "subscription_id" varchar(24) [not null]
  "created_at" datetime [not null]
}

Table "offers" {
  "id" varchar(24) [pk, not null]
  "active" tinyint(1) [not null, default: 1]
  "name" varchar(191) [unique, not null]
  "code" varchar(191) [unique, not null]
  "product_id" varchar(24)
  "stripe_coupon_id" varchar(255) [unique]
  "interval" varchar(50) [not null]
  "currency" varchar(50)
  "discount_type" varchar(50) [not null]
  "discount_amount" int [not null]
  "duration" varchar(50) [not null]
  "duration_in_months" int
  "portal_title" varchar(191)
  "portal_description" varchar(2000)
  "redemption_type" varchar(50) [not null, default: 'signup']
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "outbox" {
  "id" varchar(24) [pk, not null]
  "event_type" varchar(50) [not null]
  "status" varchar(50) [not null, default: 'pending']
  "payload" text [not null]
  "created_at" datetime [not null]
  "updated_at" datetime
  "retry_count" "int unsigned" [not null, default: 0]
  "last_retry_at" datetime
  "message" varchar(2000)

  Indexes {
    (event_type, status, created_at) [type: btree, name: "outbox_event_type_status_created_at_index"]
  }
}

Table "permissions" {
  "id" varchar(24) [pk, not null]
  "name" varchar(50) [unique, not null]
  "object_type" varchar(50) [not null]
  "action_type" varchar(50) [not null]
  "object_id" varchar(24)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "permissions_roles" {
  "id" varchar(24) [pk, not null]
  "role_id" varchar(24) [not null]
  "permission_id" varchar(24) [not null]
}

Table "permissions_users" {
  "id" varchar(24) [pk, not null]
  "user_id" varchar(24) [not null]
  "permission_id" varchar(24) [not null]
}

Table "post_revisions" {
  "id" varchar(24) [pk, not null]
  "post_id" varchar(24) [not null]
  "lexical" longtext
  "created_at_ts" bigint [not null]
  "created_at" datetime [not null]
  "author_id" varchar(24)
  "title" varchar(2000)
  "post_status" varchar(50)
  "reason" varchar(50)
  "feature_image" varchar(2000)
  "feature_image_alt" varchar(2000)
  "feature_image_caption" text
  "custom_excerpt" varchar(2000)

  Indexes {
    post_id [type: btree, name: "post_revisions_post_id_index"]
  }
}

Table "posts" {
  "id" varchar(24) [pk, not null]
  "uuid" varchar(36) [not null]
  "title" varchar(2000) [not null]
  "slug" varchar(191) [not null]
  "mobiledoc" longtext
  "lexical" longtext
  "html" longtext
  "comment_id" varchar(50)
  "plaintext" longtext
  "feature_image" varchar(2000)
  "featured" tinyint(1) [not null, default: 0]
  "type" varchar(50) [not null, default: 'post']
  "status" varchar(50) [not null, default: 'draft']
  "locale" varchar(6)
  "visibility" varchar(50) [not null, default: 'public']
  "email_recipient_filter" text [not null]
  "created_at" datetime [not null]
  "updated_at" datetime
  "published_at" datetime
  "published_by" varchar(24)
  "custom_excerpt" varchar(2000)
  "codeinjection_head" text
  "codeinjection_foot" text
  "custom_template" varchar(100)
  "canonical_url" text
  "newsletter_id" varchar(24)
  "show_title_and_feature_image" tinyint(1) [not null, default: 1]

  Indexes {
    published_at [type: btree, name: "posts_published_at_index"]
    (type, updated_at, status) [type: btree, name: "posts_type_status_updated_at_index"]
    updated_at [type: btree, name: "posts_updated_at_index"]
    uuid [type: btree, name: "posts_uuid_index"]
    (slug, type) [unique, name: "posts_slug_type_unique"]
  }
}

Table "posts_authors" {
  "id" varchar(24) [pk, not null]
  "post_id" varchar(24) [not null]
  "author_id" varchar(24) [not null]
  "sort_order" "int unsigned" [not null, default: 0]
}

Table "posts_meta" {
  "id" varchar(24) [pk, not null]
  "post_id" varchar(24) [unique, not null]
  "og_image" varchar(2000)
  "og_title" varchar(300)
  "og_description" varchar(500)
  "twitter_image" varchar(2000)
  "twitter_title" varchar(300)
  "twitter_description" varchar(500)
  "meta_title" varchar(2000)
  "meta_description" varchar(2000)
  "email_subject" varchar(300)
  "frontmatter" text
  "feature_image_alt" varchar(2000)
  "feature_image_caption" text
  "email_only" tinyint(1) [not null, default: 0]
}

Table "posts_products" {
  "id" varchar(24) [pk, not null]
  "post_id" varchar(24) [not null]
  "product_id" varchar(24) [not null]
  "sort_order" "int unsigned" [not null, default: 0]
}

Table "posts_tags" {
  "id" varchar(24) [pk, not null]
  "post_id" varchar(24) [not null]
  "tag_id" varchar(24) [not null]
  "sort_order" "int unsigned" [not null, default: 0]

  Indexes {
    (tag_id, post_id) [type: btree, name: "posts_tags_post_id_tag_id_index"]
  }
}

Table "products" {
  "id" varchar(24) [pk, not null]
  "name" varchar(191) [not null]
  "slug" varchar(191) [unique, not null]
  "active" tinyint(1) [not null, default: 1]
  "welcome_page_url" varchar(2000)
  "visibility" varchar(50) [not null, default: 'none']
  "trial_days" "int unsigned" [not null, default: 0]
  "description" varchar(191)
  "type" varchar(50) [not null, default: 'paid']
  "currency" varchar(50)
  "monthly_price" "int unsigned"
  "yearly_price" "int unsigned"
  "created_at" datetime [not null]
  "updated_at" datetime
  "monthly_price_id" varchar(24)
  "yearly_price_id" varchar(24)
}

Table "products_benefits" {
  "id" varchar(24) [pk, not null]
  "product_id" varchar(24) [not null]
  "benefit_id" varchar(24) [not null]
  "sort_order" "int unsigned" [not null, default: 0]
}

Table "recommendation_click_events" {
  "id" varchar(24) [pk, not null]
  "recommendation_id" varchar(24) [not null]
  "member_id" varchar(24)
  "created_at" datetime [not null]
}

Table "recommendation_subscribe_events" {
  "id" varchar(24) [pk, not null]
  "recommendation_id" varchar(24) [not null]
  "member_id" varchar(24)
  "created_at" datetime [not null]
}

Table "recommendations" {
  "id" varchar(24) [pk, not null]
  "url" varchar(2000) [not null]
  "title" varchar(2000) [not null]
  "excerpt" varchar(2000)
  "featured_image" varchar(2000)
  "favicon" varchar(2000)
  "description" varchar(2000)
  "one_click_subscribe" tinyint(1) [not null, default: 0]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "redirects" {
  "id" varchar(24) [pk, not null]
  "from" varchar(191) [not null]
  "to" varchar(2000) [not null]
  "post_id" varchar(24)
  "created_at" datetime [not null]
  "updated_at" datetime

  Indexes {
    from [type: btree, name: "redirects_from_index"]
  }
}

Table "roles" {
  "id" varchar(24) [pk, not null]
  "name" varchar(50) [unique, not null]
  "description" varchar(2000)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "roles_users" {
  "id" varchar(24) [pk, not null]
  "role_id" varchar(24) [not null]
  "user_id" varchar(24) [not null]
}

Table "sessions" {
  "id" varchar(24) [pk, not null]
  "session_id" varchar(32) [unique, not null]
  "user_id" varchar(24) [not null]
  "session_data" varchar(2000) [not null]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "settings" {
  "id" varchar(24) [pk, not null]
  "group" varchar(50) [not null, default: 'core']
  "key" varchar(50) [unique, not null]
  "value" text
  "type" varchar(50) [not null]
  "flags" varchar(50)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "snippets" {
  "id" varchar(24) [pk, not null]
  "name" varchar(191) [unique, not null]
  "mobiledoc" longtext [not null]
  "lexical" longtext
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "stripe_prices" {
  "id" varchar(24) [pk, not null]
  "stripe_price_id" varchar(255) [unique, not null]
  "stripe_product_id" varchar(255) [not null]
  "active" tinyint(1) [not null]
  "nickname" varchar(255)
  "currency" varchar(191) [not null]
  "amount" int [not null]
  "type" varchar(50) [not null, default: 'recurring']
  "interval" varchar(50)
  "description" varchar(191)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "stripe_products" {
  "id" varchar(24) [pk, not null]
  "product_id" varchar(24)
  "stripe_product_id" varchar(255) [unique, not null]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "subscriptions" {
  "id" varchar(24) [pk, not null]
  "type" varchar(50) [not null]
  "status" varchar(50) [not null]
  "member_id" varchar(24) [not null]
  "tier_id" varchar(24) [not null]
  "cadence" varchar(50)
  "currency" varchar(50)
  "amount" int
  "payment_provider" varchar(50)
  "payment_subscription_url" varchar(2000)
  "payment_user_url" varchar(2000)
  "offer_id" varchar(24)
  "expires_at" datetime
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "suppressions" {
  "id" varchar(24) [pk, not null]
  "email" varchar(191) [unique, not null]
  "email_id" varchar(24)
  "reason" varchar(50) [not null]
  "created_at" datetime [not null]
}

Table "tags" {
  "id" varchar(24) [pk, not null]
  "name" varchar(191) [not null]
  "slug" varchar(191) [unique, not null]
  "description" text
  "feature_image" varchar(2000)
  "parent_id" varchar(191)
  "visibility" varchar(50) [not null, default: 'public']
  "og_image" varchar(2000)
  "og_title" varchar(300)
  "og_description" varchar(500)
  "twitter_image" varchar(2000)
  "twitter_title" varchar(300)
  "twitter_description" varchar(500)
  "meta_title" varchar(2000)
  "meta_description" varchar(2000)
  "codeinjection_head" text
  "codeinjection_foot" text
  "canonical_url" varchar(2000)
  "accent_color" varchar(50)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "tokens" {
  "id" varchar(24) [pk, not null]
  "token" varchar(32) [not null]
  "uuid" varchar(36) [unique, not null]
  "data" varchar(2000)
  "created_at" datetime [not null]
  "updated_at" datetime
  "first_used_at" datetime
  "used_count" "int unsigned" [not null, default: 0]
  "otc_used_count" "int unsigned" [not null, default: 0]

  Indexes {
    token [type: btree, name: "tokens_token_index"]
  }
}

Table "users" {
  "id" varchar(24) [pk, not null]
  "name" varchar(191) [not null]
  "slug" varchar(191) [unique, not null]
  "password" varchar(60) [not null]
  "email" varchar(191) [unique, not null]
  "profile_image" varchar(2000)
  "cover_image" varchar(2000)
  "bio" text
  "website" varchar(2000)
  "location" text
  "facebook" varchar(2000)
  "twitter" varchar(2000)
  "threads" varchar(191)
  "bluesky" varchar(191)
  "mastodon" varchar(191)
  "tiktok" varchar(191)
  "youtube" varchar(191)
  "instagram" varchar(191)
  "linkedin" varchar(191)
  "accessibility" text
  "status" varchar(50) [not null, default: 'active']
  "locale" varchar(6)
  "visibility" varchar(50) [not null, default: 'public']
  "meta_title" varchar(2000)
  "meta_description" varchar(2000)
  "tour" text
  "last_seen" datetime
  "comment_notifications" tinyint(1) [not null, default: 1]
  "free_member_signup_notification" tinyint(1) [not null, default: 1]
  "paid_subscription_started_notification" tinyint(1) [not null, default: 1]
  "paid_subscription_canceled_notification" tinyint(1) [not null, default: 0]
  "mention_notifications" tinyint(1) [not null, default: 1]
  "recommendation_notifications" tinyint(1) [not null, default: 1]
  "milestone_notifications" tinyint(1) [not null, default: 1]
  "donation_notifications" tinyint(1) [not null, default: 1]
  "gift_subscription_purchase_notification" tinyint(1) [not null, default: 1]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "webhooks" {
  "id" varchar(24) [pk, not null]
  "event" varchar(50) [not null]
  "target_url" varchar(2000) [not null]
  "name" varchar(191)
  "secret" varchar(191)
  "api_version" varchar(50) [not null, default: 'v2']
  "integration_id" varchar(24) [not null]
  "last_triggered_at" datetime
  "last_triggered_status" varchar(50)
  "last_triggered_error" varchar(50)
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "welcome_email_automated_emails" {
  "id" varchar(24) [pk, not null]
  "welcome_email_automation_id" varchar(24) [not null]
  "next_welcome_email_automated_email_id" varchar(24)
  "delay_days" "int unsigned" [not null]
  "subject" varchar(300) [not null]
  "lexical" longtext
  "sender_name" varchar(191)
  "sender_email" varchar(191)
  "sender_reply_to" varchar(191)
  "email_design_setting_id" varchar(24) [not null]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Table "welcome_email_automation_runs" {
  "id" varchar(24) [pk, not null]
  "welcome_email_automation_id" varchar(24) [not null]
  "member_id" varchar(24) [not null]
  "next_welcome_email_automated_email_id" varchar(24)
  "ready_at" datetime
  "step_started_at" datetime
  "step_attempts" "int unsigned" [not null, default: 0]
  "exit_reason" varchar(50)
  "created_at" datetime [not null]
  "updated_at" datetime

  Indexes {
    ready_at [type: btree, name: "welcome_email_automation_runs_ready_at_index"]
  }
}

Table "welcome_email_automations" {
  "id" varchar(24) [pk, not null]
  "status" varchar(50) [not null, default: 'inactive']
  "name" varchar(191) [unique, not null]
  "slug" varchar(191) [unique, not null]
  "created_at" datetime [not null]
  "updated_at" datetime
}

Ref "automated_email_recipients_automated_email_id_foreign":"welcome_email_automated_emails"."id" < "automated_email_recipients"."automated_email_id"

Ref "collections_posts_collection_id_foreign":"collections"."id" < "collections_posts"."collection_id" [delete: cascade]

Ref "collections_posts_post_id_foreign":"posts"."id" < "collections_posts"."post_id" [delete: cascade]

Ref "comment_likes_comment_id_foreign":"comments"."id" < "comment_likes"."comment_id" [delete: cascade]

Ref "comment_likes_member_id_foreign":"members"."id" < "comment_likes"."member_id" [delete: cascade]

Ref "comment_reports_comment_id_foreign":"comments"."id" < "comment_reports"."comment_id" [delete: cascade]

Ref "comment_reports_member_id_foreign":"members"."id" < "comment_reports"."member_id" [delete: set null]

Ref "comments_in_reply_to_id_foreign":"comments"."id" < "comments"."in_reply_to_id" [delete: set null]

Ref "comments_member_id_foreign":"members"."id" < "comments"."member_id" [delete: set null]

Ref "comments_parent_id_foreign":"comments"."id" < "comments"."parent_id" [delete: cascade]

Ref "comments_post_id_foreign":"posts"."id" < "comments"."post_id" [delete: cascade]

Ref "donation_payment_events_member_id_foreign":"members"."id" < "donation_payment_events"."member_id" [delete: set null]

Ref "email_batches_email_id_foreign":"emails"."id" < "email_batches"."email_id"

Ref "email_recipient_failures_email_id_foreign":"emails"."id" < "email_recipient_failures"."email_id"

Ref "email_recipient_failures_email_recipient_id_foreign":"email_recipients"."id" < "email_recipient_failures"."email_recipient_id"

Ref "email_recipients_batch_id_foreign":"email_batches"."id" < "email_recipients"."batch_id"

Ref "email_recipients_email_id_foreign":"emails"."id" < "email_recipients"."email_id"

Ref "email_spam_complaint_events_email_id_foreign":"emails"."id" < "email_spam_complaint_events"."email_id"

Ref "email_spam_complaint_events_member_id_foreign":"members"."id" < "email_spam_complaint_events"."member_id" [delete: cascade]

Ref "emails_newsletter_id_foreign":"newsletters"."id" < "emails"."newsletter_id"

Ref "gifts_tier_id_foreign":"products"."id" < "gifts"."tier_id"

Ref "gifts_buyer_member_id_foreign":"members"."id" < "gifts"."buyer_member_id" [delete: set null]

Ref "gifts_redeemer_member_id_foreign":"members"."id" < "gifts"."redeemer_member_id" [delete: set null]

Ref "members_cancel_events_member_id_foreign":"members"."id" < "members_cancel_events"."member_id" [delete: cascade]

Ref "members_click_events_member_id_foreign":"members"."id" < "members_click_events"."member_id" [delete: cascade]

Ref "members_click_events_redirect_id_foreign":"redirects"."id" < "members_click_events"."redirect_id" [delete: cascade]

Ref "members_created_events_member_id_foreign":"members"."id" < "members_created_events"."member_id" [delete: cascade]

Ref "members_email_change_events_member_id_foreign":"members"."id" < "members_email_change_events"."member_id" [delete: cascade]

Ref "members_feedback_member_id_foreign":"members"."id" < "members_feedback"."member_id" [delete: cascade]

Ref "members_feedback_post_id_foreign":"posts"."id" < "members_feedback"."post_id" [delete: cascade]

Ref "members_labels_member_id_foreign":"members"."id" < "members_labels"."member_id" [delete: cascade]

Ref "members_labels_label_id_foreign":"labels"."id" < "members_labels"."label_id" [delete: cascade]

Ref "members_login_events_member_id_foreign":"members"."id" < "members_login_events"."member_id" [delete: cascade]

Ref "members_newsletters_member_id_foreign":"members"."id" < "members_newsletters"."member_id" [delete: cascade]

Ref "members_newsletters_newsletter_id_foreign":"newsletters"."id" < "members_newsletters"."newsletter_id" [delete: cascade]

Ref "members_paid_subscription_events_member_id_foreign":"members"."id" < "members_paid_subscription_events"."member_id" [delete: cascade]

Ref "members_payment_events_member_id_foreign":"members"."id" < "members_payment_events"."member_id" [delete: cascade]

Ref "members_product_events_member_id_foreign":"members"."id" < "members_product_events"."member_id" [delete: cascade]

Ref "members_product_events_product_id_foreign":"products"."id" < "members_product_events"."product_id"

Ref "members_products_member_id_foreign":"members"."id" < "members_products"."member_id" [delete: cascade]

Ref "members_products_product_id_foreign":"products"."id" < "members_products"."product_id" [delete: cascade]

Ref "members_status_events_member_id_foreign":"members"."id" < "members_status_events"."member_id" [delete: cascade]

Ref "members_stripe_customers_member_id_foreign":"members"."id" < "members_stripe_customers"."member_id" [delete: cascade]

Ref "members_stripe_customers_subscriptions_customer_id_foreign":"members_stripe_customers"."customer_id" < "members_stripe_customers_subscriptions"."customer_id" [delete: cascade]

Ref "mscs_ghost_subscription_id_foreign":"subscriptions"."id" < "members_stripe_customers_subscriptions"."ghost_subscription_id" [delete: cascade]

Ref "members_stripe_customers_subscriptions_offer_id_foreign":"offers"."id" < "members_stripe_customers_subscriptions"."offer_id"

Ref "members_subscribe_events_newsletter_id_foreign":"newsletters"."id" < "members_subscribe_events"."newsletter_id"

Ref "members_subscribe_events_member_id_foreign":"members"."id" < "members_subscribe_events"."member_id" [delete: cascade]

Ref "members_subscription_created_events_member_id_foreign":"members"."id" < "members_subscription_created_events"."member_id" [delete: cascade]

Ref "members_subscription_created_events_subscription_id_foreign":"members_stripe_customers_subscriptions"."id" < "members_subscription_created_events"."subscription_id" [delete: cascade]

Ref "offer_redemptions_member_id_foreign":"members"."id" < "offer_redemptions"."member_id" [delete: cascade]

Ref "offer_redemptions_offer_id_foreign":"offers"."id" < "offer_redemptions"."offer_id" [delete: cascade]

Ref "offer_redemptions_subscription_id_foreign":"members_stripe_customers_subscriptions"."id" < "offer_redemptions"."subscription_id" [delete: cascade]

Ref "offers_product_id_foreign":"products"."id" < "offers"."product_id"

Ref "post_revs_author_id_foreign":"users"."id" < "post_revisions"."author_id"

Ref "posts_newsletter_id_foreign":"newsletters"."id" < "posts"."newsletter_id"

Ref "posts_authors_author_id_foreign":"users"."id" < "posts_authors"."author_id"

Ref "posts_authors_post_id_foreign":"posts"."id" < "posts_authors"."post_id"

Ref "posts_meta_post_id_foreign":"posts"."id" < "posts_meta"."post_id"

Ref "posts_products_post_id_foreign":"posts"."id" < "posts_products"."post_id" [delete: cascade]

Ref "posts_products_product_id_foreign":"products"."id" < "posts_products"."product_id" [delete: cascade]

Ref "posts_tags_tag_id_foreign":"tags"."id" < "posts_tags"."tag_id"

Ref "posts_tags_post_id_foreign":"posts"."id" < "posts_tags"."post_id"

Ref "products_benefits_benefit_id_foreign":"benefits"."id" < "products_benefits"."benefit_id" [delete: cascade]

Ref "products_benefits_product_id_foreign":"products"."id" < "products_benefits"."product_id" [delete: cascade]

Ref "recommendation_click_events_member_id_foreign":"members"."id" < "recommendation_click_events"."member_id" [delete: set null]

Ref "recommendation_click_events_recommendation_id_foreign":"recommendations"."id" < "recommendation_click_events"."recommendation_id" [delete: cascade]

Ref "recommendation_subscribe_events_member_id_foreign":"members"."id" < "recommendation_subscribe_events"."member_id" [delete: set null]

Ref "recommendation_subscribe_events_recommendation_id_foreign":"recommendations"."id" < "recommendation_subscribe_events"."recommendation_id" [delete: cascade]

Ref "redirects_post_id_foreign":"posts"."id" < "redirects"."post_id" [delete: set null]

Ref "stripe_prices_stripe_product_id_foreign":"stripe_products"."stripe_product_id" < "stripe_prices"."stripe_product_id"

Ref "stripe_products_product_id_foreign":"products"."id" < "stripe_products"."product_id"

Ref "subscriptions_member_id_foreign":"members"."id" < "subscriptions"."member_id" [delete: cascade]

Ref "subscriptions_tier_id_foreign":"products"."id" < "subscriptions"."tier_id"

Ref "subscriptions_offer_id_foreign":"offers"."id" < "subscriptions"."offer_id"

Ref "suppressions_email_id_foreign":"emails"."id" < "suppressions"."email_id"

Ref "webhooks_integration_id_foreign":"integrations"."id" < "webhooks"."integration_id" [delete: cascade]

Ref "weae_automation_id_foreign":"welcome_email_automations"."id" < "welcome_email_automated_emails"."welcome_email_automation_id" [delete: cascade]

Ref "weae_next_email_id_foreign":"welcome_email_automated_emails"."id" < "welcome_email_automated_emails"."next_welcome_email_automated_email_id"

Ref "welcome_email_automated_emails_email_design_setting_id_foreign":"email_design_settings"."id" < "welcome_email_automated_emails"."email_design_setting_id"

Ref "wear_automation_id_foreign":"welcome_email_automations"."id" < "welcome_email_automation_runs"."welcome_email_automation_id" [delete: cascade]

Ref "wear_member_id_foreign":"members"."id" < "welcome_email_automation_runs"."member_id" [delete: cascade]

Ref "wear_next_email_id_foreign":"welcome_email_automated_emails"."id" < "welcome_email_automation_runs"."next_welcome_email_automated_email_id"
